# ===== Сервер =====
server.port=8080

# ===== База данных (PostgreSQL в Docker) =====
spring.datasource.url=jdbc:postgresql://localhost:5433/diploma_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=none

# ===== Liquibase (миграции БД) =====
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# ===== Хранение изображений =====
app.images.storage-path=./images

# ===== Лимиты загрузки файлов =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB